config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :friend_requests
  get 'friends/index'
  delete 'friends/destroy/:id' => 'friends#destroy', :as => 'friends_destroy'
  
  
  root 'posts#title'
  
  get 'posts/cosmetic_table'
  get 'posts/cosmetic_table/:id' => 'posts#cosmetic_table'
  get 'posts/table_move'
  get 'posts/new'
  post 'posts/create'
  get 'posts/edit/:id' => 'posts#edit'
  patch 'posts/update/:id' => 'posts#update'
  get 'posts/destroy/:id' => 'posts#destroy'
  get 'posts/janenewmypage' => 'posts#janenewmypage', :as => "posts_mypage"
  

end

app/models/friend_request.rb
class FriendRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User'
  
  # FriendRequest 클래스의 이 method는 
  # 친구신청을 받아들여 Friendships table에 편입시킨뒤, 신청기록을 없앤다.
  def accept
    user.friends << friend
    destroy
  end
  
  
  
  # add some validations to the models (uniqueness and presence)
  validates :user, presence: true
  validates :friend, presence: true, uniqueness: { scope: :user }
  
  # self-association을 막기 위한 코드(not_self)
  validate :not_self
  
  # 이미 보낸 친구신청이나, 이미 존재하는 친구에게 신청하는걸 막기 위한 코드(not_friends, not_pending)
  validate :not_friends
  validate :not_pending
  
  
  
  private
  
  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end
  
  def not_friends
    errors.add(:friend, 'is already added') if user.friends.include?(friend)
  end

  def not_pending
    errors.add(:friend, 'already requested friendship') if friend.pending_friends.include?(user)
  end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
    before_action :set_friend_request, only: [:show, :edit, :update, :destroy]
    
    def index
        if user_signed_in?
            @incomings = FriendRequest.where(friend: current_user)
            @outgoings = current_user.friend_requests
        end
    end
    
    def new
    end
    
    def create
        friend = User.find(params[:friend_id])
        @friend_request = current_user.friend_requests.new(friend: friend)
        
        respond_to do |format|
          if @friend_request.save
            format.html { redirect_to friend_requests_path, notice: '친구 신청 완료!' }
            format.json { render :show, status: :created, location: @friend_request }
          else
            format.html { redirect_to friend_requests_path, notice: '친구 신청 실패!' }
            format.json { render json: @friend_request.errors, status: :unprocessable_entity }
          end
        end
    end
    
    def show
    end
    
    def edit
    end
    
    def destroy
        @friend_request.destroy
        head :no_content
    end
    
    def update
        @friend_request.accept
        head :no_content
    end



    private
    def set_friend_request
        @friend_request = FriendRequest.find(params[:id])
    end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/index.html.erb
<p id="notice"><%= notice %></p>
<h1>친구 요청을 볼 수 있는 페이지</h1>

<% if user_signed_in? %>
    <p>
      요청 온 것!<br>
      <% if @incomings.empty? %>
        대기중인 친구 요청이 없습니다.
      <% else %>
        <p>
          <% @incomings.each do |incoming| %>
            <%= User.find(incoming.user_id).nickname %>님이 친구 요청을 했습니다.
            <%= link_to "친구신청 수락", friend_request_path(:id => incoming.id), :method => :put %>
            <%= link_to "친구신청 거절", friend_request_path(:id => incoming.id), :method => :delete %>
          <% end %>
        </p>
      <% end %>
    </p>

    <p>
      내가 요청한 것!<br>
    
      <% if @outgoings.empty? %>
        대기중인 친구 요청이 없습니다.
      <% else %>
        <% @outgoings.each do |outgoing| %>
          <%= User.find(outgoing.friend_id).nickname %>님께 친구 요청을 했습니다.
          <%= link_to "친구신청 취소", friend_request_path(:id => outgoing.id), :method => :delete %>
        <% end %>
      <% end %>
    </p>
    
    <p>
      <!--<%= link_to "친구요청 보내러가기", new_friend_request_path %>-->
    </p>
    <p>
      <%= link_to "친구목록", friends_index_path %>
    </p>
<% else %>
    로그인을 해주세요!
<% end %>

app/views/friend_requests/new.html.erb
<h1>친구 요청을 보내는 페이지</h1>

<% for user in User.all %>
  <p>
    <strong><%= user.nickname %></strong>
    <%= link_to "친구요청 보내기", friend_requests_path(friend_id: user.id), :method => :post %>
  </p>
<% end %>