config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :friend_requests
  get 'friends/index'
  delete 'friends/destroy/:id' => 'friends#destroy', :as => 'friends_destroy'
  
  
  root 'posts#title'
  
  get 'posts/cosmetic_table'
  get 'posts/cosmetic_table/:id' => 'posts#cosmetic_table'
  get 'posts/table_move'
  get 'posts/new'
  post 'posts/create'
  get 'posts/edit/:id' => 'posts#edit'
  patch 'posts/update/:id' => 'posts#update'
  get 'posts/destroy/:id' => 'posts#destroy'
  get 'posts/janenewmypage' => 'posts#janenewmypage', :as => "posts_mypage"
  

end

app/models/post.rb
class Post < ActiveRecord::Base
    mount_uploader :img_url, ImageUploader
    belongs_to :user
    
    validates :title, :category, :open_date, :exp_date, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def title
  end
  
  def cosmetic_table
    if params[:id].present?    #1 화장대 이동링크
      if user_signed_in?    #1-1 로그인 상태
        if params[:id] == current_user.id     #1-1-1 내 화장대로 이동
          @nickname = current_user.nickname
          @posts = Post.where(user_id:current_user.id)
          @friends_icon = friend_requests_path
          @friends_icon_comment = "친구관리"
          @friends_method = "get"
        else                                  #1-1-2 타인 화장대로 이동
          user_id = params[:id] 
          @nickname = User.find(user_id).nickname
          @posts = Post.where(user_id:user_id)
          @friends_icon = friend_requests_path(friend_id: user_id)
          @friends_icon_comment = "친구신청"
          @friends_method = "post"
        end
      else                  #1-2 비로그인 상태 => 타인 화장대로 이동
          user_id = params[:id] 
          @nickname = User.find(user_id).nickname
          @posts = Post.where(user_id:user_id)
      end
    else    #2 타이틀에서 화장대이동
      if user_signed_in?    #2-1 로그인 상태 => 내 화장대로 이동
        @nickname = current_user.nickname
        @posts = Post.where(user_id:current_user.id)
        @friends_icon = friend_requests_path
        @friends_icon_comment = "친구관리"
        @friends_method = "get"
      else                  #2-2 비로그인 상태 => 견본 화장대로 이동
        @nickname = "견본화장대"
        @posts = Post.all
      end
    end
  end
  
  def table_move
  end
  
  def janenewmypage
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end

  def create
    post = Post.new
    post.title = params[:post][:title]
    post.memo = params[:post][:memo]
    post.category = params[:post][:category]
    
    if params[:post][:"open_date(1i)"].present? && params[:post][:"open_date(2i)"].present? && params[:post][:"open_date(3i)"].present?
      open_date = Date.new(params[:post][:"open_date(1i)"].to_i, params[:post][:"open_date(2i)"].to_i, params[:post][:"open_date(3i)"].to_i) 
      post.open_date = open_date
    end
    if params[:post][:"exp_date(1i)"].present? && params[:post][:"exp_date(2i)"].present? && params[:post][:"exp_date(3i)"].present?
      exp_date = Date.new(params[:post][:"exp_date(1i)"].to_i, params[:post][:"exp_date(2i)"].to_i, params[:post][:"exp_date(3i)"].to_i) 
      post.exp_date = exp_date
    end
    
    post.public = params[:post][:public]
    post.user_id = params[:post][:user_id]
    post.img_url = params[:post][:image]
    post.save
    redirect_to posts_cosmetic_table_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.title = params[:post][:title]
    post.memo = params[:post][:content]
    if !params[:post][:image].nil?
      post.img_url = params[:post][:image]
    end
    post.save
    redirect_to '/'
  end

  def destroy
    Post.find(params[:id]).destroy
    redirect_to '/'
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/cosmetic_table.html.erb
<!--카루셀 화장대-->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval='false'>
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
      
    <!--page number 1 -->
    <div class="carousel-item active"> 
        <div class='firstpage'>
            <div class='top'>
                <div class='item left'>
                    <div class="floor one">
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        
                    </div>
                    <div class="floor two">
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        
                    </div>
                </div>
                <div class="item middle"><br><br><br><br>
                    <div class='aaa'>
                        <div class='bbb'>
                            <% if user_signed_in? %>
                                <a href='/friends/index'><img src='/lifeitem_icon.png'></a>
                            <% end %>
                        </div>
                    </div>
                    <div class="profile"><img src="/user.png" width="100" height="100"></div><br>
                    <div class="profile info">
                        <h1>
                            <%= @nickname %>
                        </h1>
                    </div>
                    <br>
                    <div class='friendsandlifetem'>
                        <% if user_signed_in? %>
                            <%= link_to(image_tag("/friends_icon.png", :class => "friends_icon", height: '32', width: '32'), @friends_icon, :method => @friends_method) %>
                            <%= @friends_icon_comment %>
                        <% end %>
                    </div>
                </div>
                
                <div class="item right">
                    <div class="floor three">
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                    </div>
                    <div class="floor four">
                
                        <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                        <div id="modal-container">
                          <div class="modal-background" >
                            <div class="modal">
                                <% @posts.each_with_index do |p,index| %>
                                    <h3><%=p.title%></h3>
                                    <p><%=p.memo%></p>
                                    <img src=<%=p.img_url.hi%>>
                                    <a href="/posts/edit/<%=p.id%>">[수정]</a><br>
                                    <a href="/posts/destroy/<%=p.id%>">[삭제]</a><br>
                                    <svg class="modal-svg" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" preserveAspectRatio="none">
                                    <rect x="0" y="0" fill="none" width="226" height="162" rx="3" ry="3"></rect>
                                    </svg>
                                <%end%>
                            </div>
                          </div>
                        </div>
                        <div class="content">
                          <div class="buttons">
                            <% @posts.each_with_index do |p,index| %>
                                <div id='two' class='button div2' ondrop="drop(event)" ondragover="allowDrop(event)">
                                    <img src=<%=p.img_url.thumb%>>
                                </div>
                            <% end %>
                            <div id="two" class="button"></div>
                          </div>
                        </div>
                        
                        <!--이 자바스크립트는 모달임-->
                        <script type='text/javascript'>
                        $('.button').click(function(){
                          var buttonId = $(this).attr('id');
                          $('#modal-container').removeAttr('class').addClass(buttonId);
                          $('body').addClass('modal-active');
                        })
                        
                        $('#modal-container').click(function(){
                          $(this).addClass('out');
                          $('body').removeClass('modal-active');
                        });
                        </script>
                        
                                                
                    </div>
                </div>            
            </div>
            <div class="bottom">
                <div class="floor five">
                        <% @posts.each_with_index do |p,index| %>
                            <div class="box boxdrag <%=index%>" ondrop="drop(event)" ondragover="allowDrop(event)">
                              <a href='posts/indextitle/<%=p.id%>'><img src=<%=p.img_url.thumb%> draggable="true" ondragstart="drag(event)" id="drag<%=index%>"></a>
                            </div>
                        <%end%> 
                </div>
            </div>
        </div>
    </div>      
      
    <!--page number 2-->
    <div class="carousel-item rightside">
        <div class='firstpage'>
            <div class='top'>
                <div class="pageright">
                    <div class="topright floorside">
                        <% @posts.each_with_index do |p,index| %>
                            <div class='box <%=index+1%>'><img src=<%=p.img_url.thumb%>></div>
                        <% end %>
                    </div>
                    <div class="middleright floorside"></div>
                </div>            
            </div>
            
            <div class="bottom">
                <div class="bottomright floorside"></div>
            </div>
            
        </div>
    </div>
          
    <!--page number 3-->
    <div class="carousel-item leftside">
        <div class='firstpage'>
            <div class='top'>
                <div class="pageright">
                    <div class="topleft floorside">
                        <% @posts.each_with_index do |p,index| %>
                            <div class='box <%=index+1%>'><img src=<%=p.img_url.thumb%>></div>
                        <% end %>
                    </div>
                    <div class="middleleft floorside"></div>
                </div>            
            </div>
            
            <div class="bottom">
                <div class="bottomleft floorside"></div>
            </div>
            
        </div>
    </div>    
  </div>
  
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev" style="width: 5%;">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next" style="width: 5%;">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<!--스크롤하면 bottom nav 투명해지는거 자바스크립트-->
<script type='text/javascript'>
    $(document).ready(function() {
      $(window).scroll(function() {
        if ($(this).scrollTop() > 0) {
          $('footer').css('opacity', 0);
        } else {
          $('footer').css('opacity', 1);
        }
      });
    });
</script>

<div class="bottombottomnavbar">
    <div class='bottomnavhome'><%= link_to "홈", root_path %></div>
    <div class='bottomnavregister'><%= link_to "등록하기", posts_new_path %></div>
    <div class='bottomnavmypage'><%= link_to "마이페이지", posts_mypage_path %></div>
</div>




<p id="notice"><%= notice %></p>
  <% if user_signed_in? %>
      <%= current_user.email %>
      <%= link_to "로그아웃하기", destroy_user_session_path(redirect_to: request.path) %><br>
  <% else %>
      <p>당신은 현재 로그인이 필요하군요</p>
      <%= link_to '로그인', new_user_session_path(redirect_to: request.path) %><br>
      <%= link_to '회원가입', new_user_registration_path(redirect_to: request.path) %><br>
<%end%>

<h4>
    <p>
        <a href="/posts/new">화장품 등록하기</a>
    </p>
    <p>
        <a href='/posts/janenewmypage'>내 새로운 마이페이지로 고!</a>
    </p>
    <p>
        <%= link_to '내 화장대로 이동하기', posts_cosmetic_table_path %>
    </p>
    <p>
        <a href='/posts/table_move'>다른 사람 화장대 구경하기</a>
    </p>
</h4>

<!--드래그앤드롭 예제 해본다 재인-->
<!DOCTYPE HTML>
<html>
  
<head>
<script>
function allowDrop(ev) {
    ev.preventDefault();
}

function drag(ev) {
    ev.dataTransfer.setData("text", ev.target.id);
}

function drop(ev) {
    ev.preventDefault();
    var data = ev.dataTransfer.getData("text");
    ev.target.appendChild(document.getElementById(data));
}
</script>
</head>

<body>
<h2>Drag and Drop</h2>
<p>Drag the image back and forth between the two div elements.</p>
<% @posts.each_with_index do |p,index| %>
<div class="boxdrag <%=index%>" ondrop="drop(event)" ondragover="allowDrop(event)">
  <a href='posts/indextitle/<%=p.id%>'><img src=<%=p.img_url.thumb%> draggable="true" ondragstart="drag(event)" id="drag<%=index%>"></a>
</div>
<%end%>

<div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>

</body>
</html>

app/views/posts/edit.html.erb
<h1>글쓰기</h1>
<%= form_for @post, url: "/posts/update/#{@post.id}" do |f| %>
    <%= f.text_field :title, style: "width: 400px; height: 50px" %><br><br>
    <%= f.text_area :memo, style: "width: 400px; height: 100px" %><br>
    <%= f.file_field :image, value: @post.img_url%>
    <%= f.submit '작성' %>
<% end %>

app/views/posts/janenewmypage.html.erb
<!--요기까지-->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval='false'>
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
        <div class='firstpage'>
            <div class='top'>
                <div class='item left'>
                    <div class="floor one">
                    <% @posts.each_with_index do |p,index| %>
                        <a class='button' href='/posts/indextitle/<%=p.id%>'><div class=' box <%=index+1%>'><img src=<%=p.img_url.thumb%>></div></a>
                    <% end %>
                    </div>
                    <div class="floor two"></div>
                </div>
                <div class="item middle"><br><br>
                    <div class="profile"><img src="/user.png" width="100" height="100"></div><br>
                    <div class="profile info">이재인</div><br><br>
                    <div class="page info">색조 화장품 위주 페이지</div>
                    <div class='condition'>나는 에뛰드를 좋아해요!</div>
                    <div>친구 화장대 보기 버튼</div>
                </div>
                <div class="item right">
                    <div class="floor three">
                        <!--<% @posts.each_with_index do |p,index| %>-->
                        <!--<div class="boxdrag <%=index%>" ondrop="drop(event)" ondragover="allowDrop(event)">-->
                        <!--  <a href='posts/indextitle/<%=p.id%>'><img src=<%=p.img_url.thumb%> draggable="true" ondragstart="drag(event)" id="drag<%=index%>"></a>-->
                        <!--</div>-->
                        <!--<%end%>-->
                    </div>
                    <div class="floor four"></div>
                </div>            
            </div>
            <div class="bottom">
                <div class="floor five"></div>
            </div>
            
        </div>
    </div>      
      
      
    <div class="carousel-item rightside">
        <div class='firstpage'>
            <div class='top'>
                <div class="pageright">
                    <div class="topright floorside">
                        <% @posts.each_with_index do |p,index| %>
                            <div class='box <%=index+1%>'><img src=<%=p.img_url.thumb%>></div>
                        <% end %>
                    </div>
                    <div class="middleright floorside"></div>
                </div>            
            </div>
            
            <div class="bottom">
                <div class="bottomright floorside"></div>
            </div>
            
        </div>
    </div>
          
    <div class="carousel-item leftside">
        <div class='firstpage'>
            
            <div class='top'>
                <div class="pageright">
                    <div class="topleft floorside">
                        <% @posts.each_with_index do |p,index| %>
                            <div class='box <%=index+1%>'><img src=<%=p.img_url.thumb%>></div>
                        <% end %>
                    </div>
                    <div class="middleleft floorside"></div>
                </div>            
            </div>
            
            <div class="bottom">
                <div class="bottomleft floorside"></div>
            </div>
            
        </div>
    </div>    

  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev" style="width: 5%;">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next" style="width: 5%;">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<script type='text/javascript'>
    $(document).ready(function() {
      $(window).scroll(function() {
        if ($(this).scrollTop() > 0) {
          $('header').css('opacity', 0.8);
        } else {
          $('header').css('opacity', 1);
        }
      });
    });
</script>


<div class='bottomnav'>
    <div class='bottomnavhome'>홈</div>
    <div class='bottomnavregister'>등록하기</div>
    <div class='bottomnavmypage'>마이 페이지</div>
</div>











<% @posts.each_with_index do |p,index| %>
    <a class='button' href='/posts/indextitle/<%=p.id%>'><div class=' box <%=index+1%>'><img src=<%=p.img_url.thumb%>></div></a>
<% end %>

----
<div id="modal-container">
  <div class="modal-background">
    <div class="modal">
        <% @posts.each_with_index do |p,index| %>
            <h3><%=p.title%></h3>
            <p><%=p.memo%></p>
            <img src=<%=p.img_url.hi%>>
            <a href="/posts/edit/<%=p.id%>">[수정]</a><br>
            <a href="/posts/destroy/<%=p.id%>">[삭제]</a><br>
            <svg class="modal-svg" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" preserveAspectRatio="none">
            <rect x="0" y="0" fill="none" width="226" height="162" rx="3" ry="3"></rect>
            </svg>
        <%end%>
    </div>
  </div>
</div>
<div class="content">
  <div class="buttons">
    <% @posts.each_with_index do |p,index| %>
        <div id='two' class='button'>
            <img src=<%=p.img_url.thumb%>>
        </div>
    <% end %>
    <div id="two" class="button"></div>
  </div>
</div>

<!--이 자바스크립트는 모달임-->
<script type='text/javascript'>
$('.button').click(function(){
  var buttonId = $(this).attr('id');
  $('#modal-container').removeAttr('class').addClass(buttonId);
  $('body').addClass('modal-active');
})

$('#modal-container').click(function(){
  $(this).addClass('out');
  $('body').removeClass('modal-active');
});
</script>

app/views/posts/new.html.erb
<div class='newcosmetic'>
    <h1>새로운 화장품 등록하기</h1>
    <%= form_for @post, url: '/posts/create', multipart: true do |f| %>
        <% if not user_signed_in? %>
            로그인이 필요합니다.
        <% else %>
            <%= f.text_field :title, placeholder: "화장품 이름", style: "width: 400px; height: 50px" %><br><br>
            <%= f.text_area :memo, placeholder: "메모", style: "width: 400px; height: 50px" %><br>
            
            <%= f.label :'종류' %>
            <%= f.select(:category, options_for_select(
                [
                    ["스킨", "스킨"],
                    ['로션', "로션"],
                    ['립스틱', "립스틱"],
                    ['파운데이션', "파운데이션"],
                ], 4
            )) %>
            <br>
            <%= f.label :'개봉날짜' %>
            <%= f.date_select :open_date, :use_month_numbers=>true,
                start_year: Date.today.year-10, end_year: Date.today.year+10, prompt: { year: '연도' , month: '월', day: '일'} %>
            <br>
            <%= f.label :'유통기한' %>
            <%= f.date_select :exp_date, :use_month_numbers=>true,
                start_year: Date.today.year-10, end_year: Date.today.year+10, prompt: { year: '연도' , month: '월', day: '일'} %>
            <br>
            <%= f.label :'공개여부' %>
                <%= f.radio_button(:public, true, :checked => true) %>
                <%= label_tag(:public, "공개") %>
                <%= f.radio_button(:public, false) %>
                <%= label_tag(:public, "비공개") %>    
            
            <%= f.hidden_field :user_id, value: (User.find_by email: current_user.email).id %>
            
            <%= f.file_field :image %>
            <%= f.submit '작성' %>
        <% end %>
    <% end %>
</div>

app/views/posts/table_move.html.erb
<h1>타인의 화장대로 갈 수 있는 페이지(임시)</h1>

<% if user_signed_in? %>
  <% for user in User.where.not(id:current_user.id) %>
    <p>
      <strong><%= user.nickname %></strong>
      <%= link_to "화장대 이동하기", posts_cosmetic_table_path(id: user.id) %>
    </p>
  <% end %>
<% else %>
  <% for user in User.all %>
    <p>
      <strong><%= user.nickname %></strong>
      <%= link_to "화장대 이동하기", posts_cosmetic_table_path(id: user.id) %>
    </p>
  <% end %>
<% end %>

app/views/posts/title.html.erb
<h1>타이틀화면(지상이가 만든 타이틀 들어갈 예정)</h1>

<p id="notice"><%= notice %></p>
  <% if user_signed_in? %>
      <%= current_user.email %>
      <%= link_to "로그아웃하기", destroy_user_session_path(redirect_to: request.path) %><br>
  <% else %>
      <%= link_to '로그인', new_user_session_path(redirect_to: request.path) %><br>
      <%= link_to '회원가입', new_user_registration_path(redirect_to: request.path) %><br>
<%end%>

<%= link_to '화장대로 이동하기', posts_cosmetic_table_path %>